### ISSUE TITLE
Are there any benchmarks to test.

### ISSUE THREAD

**Issue by romanholidaypancakes** [Dasaav-dsv/Pattern16#1]
This is the fastest algorithm I've ever used.
https://github.com/0x1F9F1/mem/blob/master/include/mem/simd_scanner.h

**Comment by Dasaav-dsv** [comment]
I'll preface this by saying it's hard to benchmark performance for the sake of comparing scanners, they all run pretty differently and need different things, on top of it already being difficult to benchmark the individual performance of a scanner. 
I've decided to go for a less accurate "effective speed" benchmark, which is included in source code. I also adapted the mem scanner to be compatible with that benchmarking method, so you can swap the scanner out for it and run the benchmark on that. 
From my own tests (I7 7700k, 16GB DDR4-2133), my scanner is about 40-50% faster, with top speeds of 25 GB/s when scanning executable binaries, with mem reaching up to 18 GB/s.

Also, I'm well aware of mem myself, I've used it for a long time, and it was the main scanner I benchmarked my own code against.

https://i.imgur.com/c7Gjqml.png
