### ISSUE TITLE
Crashing when the signature is not found

### ISSUE THREAD

**Issue by dnblank123** [Dasaav-dsv/Pattern16#3]
Title, might possible solution is to return nullptr when not found (?)

**Comment by Dasaav-dsv** [comment]
Returning nullptr is already the current behavior.

However, the memory in the provided region must be read to be compared to the signature. If the provided size of the region exceeds the size of the allocated memory in the region (and a matching signature is not found inside), memory that had not beed allocated will be attempted to be read and will raise an access violation. Similar issues can arise with NO_ACCESS pages or page guards within the region. 

Feel free to reach out and provide more details about your issue.

**Comment by dnblank123** [comment]
> If the provided size of the region exceeds the size of the allocated memory in the region

Hello, thanks for the reply. The region size is `SIZE_MAX`, which I didn't know was bad and changed it to the app last offset.
