### ISSUE TITLE
Unable to compile with clang-cl toolset

### ISSUE THREAD

**Issue by grazaerd** [Dasaav-dsv/Pattern16#6]
I'm using Visual Studio 2022 with clang-cl and getting errors with AVX, BMI, etc, even though the build is SSE.
![image](https://github.com/Dasaav-dsv/Pattern16/assets/67945097/5dda7a56-20fe-497b-9b2d-62483f237921)

**Comment by Dasaav-dsv** [comment]
Did you set the additional command line options to pass to clang? You can find them under Configuration Properties->C/C++->Command Line.

To enable instruction set support, for example SSE 4.2, you need to use the -msse4.2 flag (some other example flags are  -mavx2 -mavx -msse4.2 -mbmi2 -mbmi -mlzcnt and so on...).  You can also use -march=*CPU architecture*

**Comment by grazaerd** [comment]
I thought Visual Studio would set it automatically, but yeah, it works now after adding the flag. Thank you.

**Comment by grazaerd** [comment]
@Dasaav-dsv I tried to redownload the repo and build, the issue still persist even with -msse2, -msse4.1, and -msse4.2.

**Comment by Dasaav-dsv** [comment]
Can you post the build output? Keep in mind that clang-cl error detection (pre-build) is not perfect, it will say it's missing a lot of the intrinsics while actually compiling without issues

**Comment by grazaerd** [comment]
here's the build output: https://gist.github.com/dnblank123/bc896f553cfb1b8c001245b464833acd

**Comment by Dasaav-dsv** [comment]
Try with -mavx and -mlzcnt. Don't worry about building with AVX since only the available instruction sets will be used at runtime

**Comment by grazaerd** [comment]
Both errors; build output: https://gist.github.com/dnblank123/d561a5b4f195f023fb9d6947cc1c37d7

**Comment by Dasaav-dsv** [comment]
I meant with -msse4.2 -mavx -mlzcnt all at once

**Comment by grazaerd** [comment]
> -msse4.2 -mavx -mlzcnt

I tried that. Ouput: https://gist.github.com/dnblank123/ba9d0140046763676edc8d86b6cb477c
+with -msse2 and -msse4.1

**Comment by Dasaav-dsv** [comment]
Getting there, add -mbmi -mbmi2. Should hopefully be it

**Comment by grazaerd** [comment]
output: https://gist.github.com/dnblank123/9f2266903c0a5e699cfb0ffa26684e6b
update: it works now; adding some headers on avx.h and -mavx2 on command line
>#include <avxintrin.h>
>#include <avx2intrin.h>

Thank you again for helping me!
